version: '3.7'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT_ALLOW_RECOVERY=true
    networks:
      - recipe_network

networks:
  recipe_network:
    driver: bridge 